Add maven-pmd-plugin version 3.17.0
To fix java.lang.NoSuchMethodError:
org.fusesource.jansi.AnsiPrintStream org.fusesource.jansi.AnsiConsole.out()
error introduced in 3.18.0